### ISSUE TITLE
Practica con Issue y Pull Request en Index.html

### ISSUE THREAD

**Issue by josetejerina** [NozomiProjects/portfolio_template#1]
Hola compañero, procedo a realizar el ejercicio propuesto en clase.

**Comment by josetejerina** [comment]
Compañero, de momento tengo el inconveniente que se muestra en la captura. Intentare solucionarlo y cuando lo haga solicitare el pull request.
![image](https://user-images.githubusercontent.com/107653230/177401055-3cea0915-0fcb-4aac-ac25-196fcfe1f693.png)

**Comment by NozomiProjects** [comment]
Hola buenas tardes, esta bien espero no hay problema.
